# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-05 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=222, verbose_name='联系人'),
        ),
    ]
